default:
  # Official language image. Look for the different tagged releases at:
  # https://hub.docker.com/r/library/python/tags/
  image: python:3.7-buster
  interruptible: true

variables:
    DEPLOY_MULTIPLE_RELEASES:
        value: "true"
        description: Flag for deployment of multiple releases or one release.

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

stages:
  - static_analysis
  - generate_yaml
  - deploy_pipeline

shellcheck:
  stage: static_analysis
  image: pipelinecomponents/shellcheck:latest
  tags:
    - docker-runner
  script:
    - |
      find . -name .git -type d -prune -o -type f -name \*.sh -print0 |
      xargs -0 -r -n1 shellcheck -e SC1091 -e SC2024 --color

python_black:
    stage: static_analysis
    image:
      name: cytopia/black
      entrypoint: ["/bin/ash", "-c"]
    tags:
    - docker-runner
    script:
        - python3 -m black --check --diff --color .

generate_yaml_config:
    stage: generate_yaml
    script:
        - bash generate_yml.sh > release-test.yml
    artifacts:
        paths:
            - release-test.yml
            - deploy.yml

release_testing:
    stage: deploy_pipeline
    trigger:
        include:
            - artifact: release-test.yml
              job: generate_yaml_config
        strategy: depend
    variables:
        PARENT_PIPELINE_ID: $CI_PIPELINE_ID

# For 3 release pipelines.
.multiple_releases:
    stage: deploy_pipeline
    trigger:
        include: deploy-pipeline.yml
        strategy: depend
    parallel:
        matrix:
            - VM_PROFILE: [ "$VM_PROFILE_CURRENT_RELEASE", "$VM_PROFILE_PREVIOUS_RELEASE"]
              REPROVISION_SERVERS: "$REPROVISION_SERVERS"
              DOCKER_REGISTRY_PASSWORD: "$DOCKER_REGISTRY_PASSWORD"
    rules:
        - if: '($DEPLOY_MULTIPLE_RELEASES == "true")'
        
.single_release:
    stage: deploy_pipeline
    trigger:
        include: deploy-pipeline.yml
        strategy: depend
    variables:
        MULTINODE: "$MULTINODE"
        VM_PROFILE: "$VM_PROFILE"
        REPROVISION_SERVERS: "$REPROVISION_SERVERS"
        DOCKER_REGISTRY_PASSWORD: "$DOCKER_REGISTRY_PASSWORD"
    rules:
        - if: '($DEPLOY_MULTIPLE_RELEASES != "true")'
