default:
  # Official language image. Look for the different tagged releases at:
  # https://hub.docker.com/r/library/python/tags/
  image: python:3.7-buster
  # interruptible: true

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

stages:
  - static_analysis
  - tag_virtual_servers
  - deploy_pipeline

shellcheck:
  stage: static_analysis
  image: pipelinecomponents/shellcheck:latest
  tags:
    - docker-runner
  script:
    - |
      find . -name .git -type d -prune -o -type f -name \*.sh -print0 |
      xargs -0 -r -n1 shellcheck -e SC1091 -e SC2024 --color

python_black:
    stage: static_analysis
    image:
      name: cytopia/black
      entrypoint: ["/bin/ash", "-c"]
    tags:
    - docker-runner
    script:
        - python3 -m black --check --diff --color .

tag_virtual_servers:
    stage: tag_virtual_servers
    image: utsaics/maas:2.8
    tags:
        - docker-runner
    before_script:
        - pip3 install toml timeout_decorator
    script:
        - python3 -u deploy.py tag_virtual_servers --VM_PROFILE "$VM_PROFILE_CURRENT_RELEASE" --MAAS_URL "$MAAS_URL" --MAAS_API_KEY "$MAAS_API_KEY"
        - python3 -u deploy.py tag_virtual_servers --VM_PROFILE "$VM_PROFILE_PREVIOUS_RELEASE" --MAAS_URL "$MAAS_URL" --MAAS_API_KEY "$MAAS_API_KEY"
        - echo "PARENT_PROJECT_PIPELINE_ID=?" >> build.env
    artifacts:
      reports:
        dotenv: build.env


# For 3 release pipelines.
multiple_releases:
    stage: deploy_pipeline
    trigger:
        include: deploy-pipeline.yml
        strategy: depend
    parallel:
        matrix:
            - VM_PROFILE: [ "$VM_PROFILE_CURRENT_RELEASE", "$VM_PROFILE_PREVIOUS_RELEASE"]
              REPROVISION_SERVERS: "$REPROVISION_SERVERS"
              DOCKER_REGISTRY_PASSWORD: "$DOCKER_REGISTRY_PASSWORD"
    rules:
        - if: '($DEPLOY_MULTIPLE_RELEASES == "true")'
        
single_release:
    stage: deploy_pipeline
    trigger:
        include: deploy-pipeline.yml
        strategy: depend
    variables:
        MULTINODE: "$MULTINODE"
        VM_PROFILE: "$VM_PROFILE"
        REPROVISION_SERVERS: "$REPROVISION_SERVERS"
        DOCKER_REGISTRY_PASSWORD: "$DOCKER_REGISTRY_PASSWORD"
    rules:
        - if: '($DEPLOY_MULTIPLE_RELEASES != "true")'
