default:
  # Official language image. Look for the different tagged releases at:
  # https://hub.docker.com/r/library/python/tags/
  image: python:3.7-buster

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

stages:
  - static_analysis
  - deploy_pipeline

shellcheck:
  stage: static_analysis
  image: pipelinecomponents/shellcheck:latest
  tags:
    - docker-runner
  script:
    - |
      find . -name .git -type d -prune -o -type f -name \*.sh -print0 |
      xargs -0 -r -n1 shellcheck -e SC1091 -e SC2024 --color

python_black:
    stage: static_analysis
    tags:
    - docker-runner
    before_script:
      - pip3 install black
    script:
        - black --check --diff --color .

multiple_releases:
    stage: deploy_pipeline
    trigger:
        include: deploy-pipeline.yml
        strategy: depend
    parallel:
        matrix:
          - VM_PROFILE: "$VM_PROFILE_CURRENT_RELEASE"
            REPROVISION_SERVERS: "$REPROVISION_SERVERS"
            DOCKER_REGISTRY_PASSWORD: "$DOCKER_REGISTRY_PASSWORD"
          - VM_PROFILE: "$VM_PROFILE_NEXT_RELEASE"
            REPROVISION_SERVERS: "$REPROVISION_SERVERS"
            DOCKER_REGISTRY_PASSWORD: "$DOCKER_REGISTRY_PASSWORD"
          - VM_PROFILE: "$VM_PROFILE_PREVIOUS_RELEASE"
            REPROVISION_SERVERS: "$REPROVISION_SERVERS"
            DOCKER_REGISTRY_PASSWORD: "$DOCKER_REGISTRY_PASSWORD"
    rules:
        - if: '$VM_PROFILE != "" || $VM_PROFILE != null'
          when: never
        - if: '($VM_PROFILE_CURRENT_RELEASE != "" || $VM_PROFILE_CURRENT_RELEASE != null)'
          when: always
        - if: '($VM_PROFILE_NEXT_RELEASE != "" || $VM_PROFILE_NEXT_RELEASE != null)'
          when: always
        - if: '($VM_PROFILE_PREVIOUS_RELEASE != "" || $VM_PROFILE_PREVIOUS_RELEASE != null)'
          when: always
        
single_release:
    stage: deploy_pipeline
    trigger:
        include: deploy-pipeline.yml
        strategy: depend
    variables:
        REPROVISION_SERVERS: "$REPROVISION_SERVERS"
        DOCKER_REGISTRY_PASSWORD: "$DOCKER_REGISTRY_PASSWORD"
    rules:
        - if: '$VM_PROFILE == "" || $VM_PROFILE == null'
          when: never
        - when: on_success
